# base image --> ubunto
FROM ubuntu:latest    
# installs curl and bash and updates the package installer
RUN apt-get update && apt-get install -y curl  
# y for yes/no when installing in ubuntu
CMD [ "/bin/bash" ]
