networks: # define a network
  mynetwork:
    driver: bridge
volumes: # define a volume
  myvolume:
    driver: local
services:
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - '6379:6379'  # port mapping
    volumes:
      - myvolume:/database
    networks:
      - mynetwork
  web:
    build: .
    container_name: web 
    ports:
      - '5000:5000'
    depends_on:
      - redis
    networks:
      - mynetwork
    environment: # environment variables
      - PORT=5000
      - API_KEY=941DE7EE-05BE-4EAD-9543-582D3046ADFD
      - TIME_TO_EXPIRE=5
      - NAME=btc
      - ADDRESS=https://rest.coinapi.io/v1/assets/