apiVersion: v1
kind: ConfigMap
metadata:
  name: price-server-config
data:
  PORT: "5000"
  API_KEY: "941DE7EE-05BE-4EAD-9543-582D3046ADFD"
  TIME_TO_EXPIRE: "5"
  NAME: "eth"
  ADDRESS: "https://rest.coinapi.io/v1/assets/"